version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: chaoticipher
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testingdeploypsqldb
    ports:
      - "5432:5432"
    networks:
      - app-network

  jhipster:
    image: ${DOCKER_USERNAME}/testingdeploypsql:postgres
    container_name: testingdeploypsql-postgres
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testingdeploypsqldb
      SPRING_DATASOURCE_USERNAME: chaoticipher
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
